# Generated by Django 5.1.1 on 2024-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50, verbose_name='Номенклатура.Артикул')),
                ('count', models.PositiveIntegerField(verbose_name='Остаток')),
                ('name', models.CharField(max_length=100, verbose_name='Ценовая группа/ Номенклатура')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Марки')),
                ('price', models.FloatField(default=None, null=True, verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='activity_view_permission',
            field=models.ManyToManyField(blank=True, to='support.role', verbose_name='Чью активность разрешено просматривать (Влияет на доступ к меню)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='file_sharing_download_file_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность скачивать файлы в файлообменнике (Влияет на доступ к меню)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='order_view_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность просматривать заявки заказов (Влияет на доступ к меню)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='price_list_view_list_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность просматривать прайс-лист (Влияет на доступ к меню)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='trash_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность добавлять товары в корзину и оставлять заявку заказов (Влияет на доступ к меню)'),
        ),
    ]
