# Generated by Django 5.1.1 on 2024-11-07 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_productontrash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Ценовая группа/ Номенклатура')),
                ('manufacturer', models.CharField(max_length=250, null=True, verbose_name='Марки')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productontrash',
            options={'verbose_name': 'Продукт в корзине', 'verbose_name_plural': 'Продукты в корзине'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время формирования заказа')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
