# Generated by Django 5.1.1 on 2024-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_product_alter_role_activity_view_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True, verbose_name='Марки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Ценовая группа/ Номенклатура'),
        ),
    ]
