# Generated by Django 5.1.1 on 2024-10-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_product_count_alter_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(max_length=250, null=True, verbose_name='Марки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Ценовая группа/ Номенклатура'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial',
            field=models.CharField(max_length=100, verbose_name='Номенклатура.Артикул'),
        ),
    ]
