# Generated by Django 5.1.1 on 2024-11-07 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_productinorder_alter_productontrash_options_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='support.order', verbose_name='Заказ'),
        ),
    ]
