# Generated by Django 5.1.1 on 2024-10-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_role_file_sharing_delete_document_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='price_list_create_list_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность создавать прайс-листы'),
        ),
        migrations.AddField(
            model_name='role',
            name='price_list_delete_list_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность удалять прайс-листы'),
        ),
    ]
