# Generated by Django 5.1.1 on 2024-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_role_price_list_create_list_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='contacts_edit_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность редактировать контакты пользователей (Влияет на доступ к меню)'),
        ),
        migrations.AddField(
            model_name='role',
            name='contacts_view_permission',
            field=models.BooleanField(default=False, verbose_name='Возможность просматривать контакты пользователей (Влияет на доступ к меню)'),
        ),
    ]
