# Generated by Django 5.1.1 on 2024-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_role_contacts_edit_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='contacts_edit_permission',
        ),
        migrations.AddField(
            model_name='role',
            name='contacts_can_admin_view_permission',
            field=models.ManyToManyField(blank=True, related_name='Role_contacts_can_admin_view_permission', to='support.role', verbose_name='Логины и пароли каких пользователей может видеть'),
        ),
        migrations.AddField(
            model_name='role',
            name='contacts_can_edit_permission',
            field=models.ManyToManyField(blank=True, related_name='Role_contacts_can_edit_permission', to='support.role', verbose_name='Чьи аккаунты может редактировать'),
        ),
        migrations.AddField(
            model_name='role',
            name='contacts_can_view_permission',
            field=models.ManyToManyField(blank=True, related_name='Role_contacts_can_view_permission', to='support.role', verbose_name='Чьи контакты может просматривать'),
        ),
        migrations.AlterField(
            model_name='role',
            name='activity_view_permission',
            field=models.ManyToManyField(blank=True, related_name='Role_activity_view_permission', to='support.role', verbose_name='Чью активность разрешено просматривать (Влияет на доступ к меню)'),
        ),
    ]
