# Generated by Django 5.1.1 on 2024-11-07 06:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xlsx', 'xls'])], verbose_name='Файл')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='support.order', verbose_name='Заказ')),
            ],
        ),
    ]
