# Generated by Django 5.1.1 on 2024-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_role_contacts_edit_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clear_password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='role',
            name='contacts_can_admin_view_permission',
            field=models.ManyToManyField(blank=True, related_name='Role_contacts_can_admin_view_permission', to='support.role', verbose_name='Чьи логины и пароли может видеть'),
        ),
    ]
