# Generated by Django 5.1.1 on 2024-11-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_order_options_orderfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfile',
            options={'verbose_name': 'Файл заказа', 'verbose_name_plural': 'Файлы заказов'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_emails',
            field=models.BooleanField(default=False, verbose_name='Принимать письма на почту или нет'),
        ),
    ]
