# Generated by Django 5.1.1 on 2024-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_alter_activity_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doctype',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Тип файла'),
        ),
    ]
